version: '3'

services:
    backend:
        image: docker.io/pizzi1995517/backend:latest
        ports:
            - "3000:3000"
        volumes:
            - ./shared:/shared
    frontend:
        image: docker.io/pizzi1995517/frontend:latest
        ports:
            - "8080:80"
